### ISSUE TITLE
前端启动报错

### ISSUE THREAD

**Issue by AlanJava** [jishenghua/jshERP#84]
ERROR  Failed to compile with 1 errors                                                                                                       09:22:26

 error  in ./src/components/NumberInfo/NumberInfo.vue?vue&type=style&index=0&id=4370c5af&lang=less&scoped=true&

Module build failed (from ./node_modules/vue-loader/lib/loaders/stylePostLoader.js):
TypeError: Cannot set properties of undefined (setting 'parent')
    at C:\alan_work\JSH_ERP\jshERP-web\src\components\NumberInfo\NumberInfo.vue:1282:1
    at Root.insertAfter (C:\alan_work\JSH_ERP\jshERP-web\node_modules\@vue\compiler-sfc\dist\compiler-sfc.js:13933:21)
    at C:\alan_work\JSH_ERP\jshERP-web\node_modules\@vue\compiler-sfc\dist\compiler-sfc.js:17634:30
    at Selector.each (C:\alan_work\JSH_ERP\jshERP-web\node_modules\@vue\compiler-sfc\dist\compiler-sfc.js:14037:17)
    at rewriteSelector (C:\alan_work\JSH_ERP\jshERP-web\node_modules\@vue\compiler-sfc\dist\compiler-sfc.js:17566:14)
    at C:\alan_work\JSH_ERP\jshERP-web\node_modules\@vue\compiler-sfc\dist\compiler-sfc.js:17559:13
    at Root.each (C:\alan_work\JSH_ERP\jshERP-web\node_modules\@vue\compiler-sfc\dist\compiler-sfc.js:14037:17)
    at Processor.func (C:\alan_work\JSH_ERP\jshERP-web\node_modules\@vue\compiler-sfc\dist\compiler-sfc.js:17558:22)
    at Processor._runSync (C:\alan_work\JSH_ERP\jshERP-web\node_modules\@vue\compiler-sfc\dist\compiler-sfc.js:17161:27)
    at Processor.processSync (C:\alan_work\JSH_ERP\jshERP-web\node_modules\@vue\compiler-sfc\dist\compiler-sfc.js:17256:24)
    at processRule (C:\alan_work\JSH_ERP\jshERP-web\node_modules\@vue\compiler-sfc\dist\compiler-sfc.js:17561:8)
    at Rule (C:\alan_work\JSH_ERP\jshERP-web\node_modules\@vue\compiler-sfc\dist\compiler-sfc.js:17503:13)
    at LazyResult.visitSync (C:\alan_work\JSH_ERP\jshERP-web\node_modules\@vue\compiler-sfc\node_modules\postcss\lib\lazy-result.js:308:19)
    at LazyResult.walkSync (C:\alan_work\JSH_ERP\jshERP-web\node_modules\@vue\compiler-sfc\node_modules\postcss\lib\lazy-result.js:297:20)
    at C:\alan_work\JSH_ERP\jshERP-web\node_modules\@vue\compiler-sfc\node_modules\postcss\lib\lazy-result.js:291:39
    at Root.each (C:\alan_work\JSH_ERP\jshERP-web\node_modules\@vue\compiler-sfc\node_modules\postcss\lib\container.js:41:16)
    at LazyResult.walkSync (C:\alan_work\JSH_ERP\jshERP-web\node_modules\@vue\compiler-sfc\node_modules\postcss\lib\lazy-result.js:290:16)

 @ ./node_modules/vue-style-loader??ref--10-oneOf-1-0!./node_modules/css-loader??ref--10-oneOf-1-1!./node_modules/vue-loader/lib/loaders/stylePostLoad
er.js!./node_modules/postcss-loader/src??ref--10-oneOf-1-2!./node_modules/less-loader/dist/cjs.js??ref--10-oneOf-1-3!./node_modules/cache-loader/dist/
cjs.js??ref--0-0!./node_modules/vue-loader/lib??vue-loader-options!./src/components/NumberInfo/NumberInfo.vue?vue&type=style&index=0&id=4370c5af&lang=
less&scoped=true& 4:14-483 15:3-20:5 16:22-491
 @ ./src/components/NumberInfo/NumberInfo.vue?vue&type=style&index=0&id=4370c5af&lang=less&scoped=true&
 @ ./src/components/NumberInfo/NumberInfo.vue
 @ ./src lazy ^\.\/components.*$ namespace object
 @ ./src/utils/util.js
 @ ./src/permission.js
 @ ./src/main.js
 @ multi (webpack)-dev-server/client?http://172.16.1.100:3000/sockjs-node (webpack)/hot/dev-server.js ./src/main.js

**Comment by dushenyan** [comment]
node环境版本问题
